data:extend({
	{
		type = "bool-setting",
		name = "ambientlife-enable-birds",
		setting_type = "runtime-global",
		default_value = true,
		order = "a",
	},
	{
		type = "bool-setting",
		name = "ambientlife-enable-butterflies",
		setting_type = "runtime-global",
		default_value = true,
		order = "b",
	},
	{
		type = "bool-setting",
		name = "ambientlife-enable-fireflies",
		setting_type = "runtime-global",
		default_value = true,
		order = "c",
	},
	{
		type = "int-setting",
		name = "ambientlife-max-creatures",
		setting_type = "runtime-global",
		default_value = 40,
		minimum_value = 0,
		maximum_value = 200,
		order = "d",
	},
	{
		type = "double-setting",
		name = "ambientlife-density",
		setting_type = "runtime-global",
		default_value = 1.0,
		minimum_value = 0,
		maximum_value = 3,
		order = "e",
	},
	{
		type = "double-setting",
		name = "ambientlife-pollution-limit",
		setting_type = "runtime-global",
		default_value = 60,
		minimum_value = 0,
		maximum_value = 1000,
		order = "f",
	},
})
